### PR TITLE
 worked on SystemA MiddleFilter to have measurements converted

### PR DESCRIPTION
**Pull request by hangyao**
It seems not working for the last several data points?

### CODE REVIEW

**Comment by hangyao** [comment]
I think I know where the problem is!

Please don't merge until I fix it tonight!

Thanks!

**Comment by hangyao** [comment]
Problem solved. Please merge this PR.

**Review by darioalessandro — APPROVED** [review]
LGTM

**Comment by darioalessandro** [comment]
@hangyao I added you as a ```Collaborator``` you should be able to create branches in this repo.

**Pull request merged**
